[application]

# dioxus project name
name = "dioxus-tailwind"

# default platfrom
# you can also use `dioxus serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "desktop"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Dioxus ❤️ Tailwind"

index_on_404 = true

[web.watcher]

watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["public/tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[application.plugins]

available = true

required = []